### ISSUE TITLE
Super dev problems running mode GWT 2.8 rc2

### ISSUE THREAD

**Issue by javadebian** [Putnami/putnami-web-toolkit#135]
[INFO] <<< gwt-maven-plugin:2.8.0-rc1:run (default-cli) < process-classes @ LaSalle <<<
[INFO] 
[INFO] --- gwt-maven-plugin:2.8.0-rc1:run (default-cli) @ LaSalle ---
[INFO] create exploded Jetty webapp in /Volumes/Data/workspace-sts/LaSalle/target/LaSalle-0.0.1-SNAPSHOT
[INFO] Super Dev Mode starting up
[INFO]    workDir: /var/folders/ml/g0289qw932b8mppy5294nhtc0000gn/T/gwt-codeserver-4089451969354064220.tmp
[ERROR] 2016-08-21 13:13:28.743:INFO::main: Logging initialized @3437ms
[INFO]    Loading Java files in org.devart.colegio.lasalle.
[INFO]    Ignored 2 units with compilation errors in first pass.
[INFO] Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
[INFO]    Module setup completed in 37958 ms
[ERROR] 2016-08-21 13:14:05.653:INFO:oejs.Server:main: jetty-9.2.14.v20151106
[ERROR] 2016-08-21 13:14:05.693:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@3b5fd11f{/,null,AVAILABLE}
[ERROR] 2016-08-21 13:14:05.791:INFO:oejs.ServerConnector:main: Started ServerConnector@5b5b5f8d{HTTP/1.1}{127.0.0.1:9876}
[ERROR] 2016-08-21 13:14:05.793:INFO:oejs.Server:main: Started @40487ms
[INFO] 
[INFO] The code server is ready at http://127.0.0.1:9876/
[ERROR] 2016-08-21 13:14:06.040:INFO:oejs.Server:main: jetty-9.2.14.v20151106
[ERROR] 2016-08-21 13:14:06.460:INFO:oejsh.ContextHandler:main: Started c.g.g.d.s.j.WebAppContextWithReload@68a4face{/,file:/Volumes/Data/workspace-sts/LaSalle/target/LaSalle-0.0.1-SNAPSHOT/,AVAILABLE}{/Volumes/Data/workspace-sts/LaSalle/target/LaSalle-0.0.1-SNAPSHOT}
[ERROR] 2016-08-21 13:14:06.462:INFO:oejs.ServerConnector:main: Started ServerConnector@1bf5cace{HTTP/1.1}{127.0.0.1:8888}
[ERROR] 2016-08-21 13:14:06.462:INFO:oejs.Server:main: Started @41157ms
[INFO] GET /recompile/colegio
[INFO]    Job org.devart.colegio.lasalle_1_0
[INFO]       starting job: org.devart.colegio.lasalle_1_0
[INFO]       binding: formfactor=desktop
[INFO]       binding: user.agent=safari
[INFO]       Compiling module org.devart.colegio.lasalle
[INFO]          Ignored 2 units with compilation errors in first pass.
[INFO] Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
[INFO]          [ERROR] An internal compiler exception occurred
[INFO] com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:111)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:276)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
[INFO] 	at com.google.gwt.dev.jjs.ast.JCastOperation.traverse(JCastOperation.java:72)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
[INFO] 	at com.google.gwt.dev.jjs.ast.JCastOperation.traverse(JCastOperation.java:72)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethodCall.visitChildren(JMethodCall.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:266)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
[INFO] 	at com.google.gwt.dev.jjs.ast.JCastOperation.traverse(JCastOperation.java:72)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.acceptImmutable(JModVisitor.java:305)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethodCall.visitChildren(JMethodCall.java:275)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:266)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
[INFO] 	at com.google.gwt.dev.jjs.ast.JExpressionStatement.traverse(JExpressionStatement.java:42)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor$ListContext.traverse(JModVisitor.java:88)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemove(JModVisitor.java:331)
[INFO] 	at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:92)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:139)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:135)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:83)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:785)
[INFO] 	at com.google.gwt.dev.jjs.ast.JConstructor.traverse(JConstructor.java:142)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst.mainLoop(UnifyAst.java:1379)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst.exec(UnifyAst.java:875)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.unifyJavaAst(JavaToJavaScriptCompiler.java:1410)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.constructJavaAst(JavaToJavaScriptCompiler.java:1222)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:1140)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:255)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:255)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:204)
[INFO] 	at com.google.gwt.dev.codeserver.Recompiler.doCompile(Recompiler.java:362)
[INFO] 	at com.google.gwt.dev.codeserver.Recompiler.compile(Recompiler.java:175)
[INFO] 	at com.google.gwt.dev.codeserver.Recompiler.recompile(Recompiler.java:134)
[INFO] 	at com.google.gwt.dev.codeserver.Outbox.recompile(Outbox.java:135)
[INFO] 	at com.google.gwt.dev.codeserver.JobRunner.recompile(JobRunner.java:113)
[INFO] 	at com.google.gwt.dev.codeserver.JobRunner.access$000(JobRunner.java:37)
[INFO] 	at com.google.gwt.dev.codeserver.JobRunner$2.run(JobRunner.java:90)
[INFO] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[INFO] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[INFO] 	at java.lang.Thread.run(Thread.java:745)
[INFO] Caused by: java.lang.NoSuchMethodError: com.google.gwt.dev.resource.ResourceOracle.getResourceMap()Ljava/util/Map;
[INFO] 	at fr.putnami.pwt.core.widget.rebind.UiBinderLocalizedCreator.getTemplateResource(UiBinderLocalizedCreator.java:104)
[INFO] 	at fr.putnami.pwt.core.widget.rebind.UiBinderLocalizedCreator.create(UiBinderLocalizedCreator.java:71)
[INFO] 	at fr.putnami.pwt.core.widget.rebind.UiBinderLocalizedGenerator.generate(UiBinderLocalizedGenerator.java:45)
[INFO] 	at com.google.gwt.core.ext.IncrementalGenerator.generateNonIncrementally(IncrementalGenerator.java:40)
[INFO] 	at com.google.gwt.dev.javac.StandardGeneratorContext.runGeneratorIncrementally(StandardGeneratorContext.java:745)
[INFO] 	at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:103)
[INFO] 	at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:78)
[INFO] 	at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:262)
[INFO] 	at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:251)
[INFO] 	at com.google.gwt.dev.PrecompilationContextCreator$1.getAllPossibleRebindAnswers(PrecompilationContextCreator.java:86)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createStaticRebindExpression(UnifyAst.java:493)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createRebindExpression(UnifyAst.java:463)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.handleMagicMethodCall(UnifyAst.java:588)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.endVisit(UnifyAst.java:293)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:268)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	... 66 more
[INFO]             [ERROR] at initDisplay_Injector.java(15): GWT.create(initDisplay_Injector$initDisplayTemplateBinder.class)
[INFO]                com.google.gwt.dev.jjs.ast.JMethodCall
[INFO]             [ERROR] at initDisplay_Injector.java(15): (initDisplay_Injector$initDisplayTemplateBinder) GWT.create(initDisplay_Injector$initDisplayTemplateBinder.class)
[INFO]                com.google.gwt.dev.jjs.ast.JCastOperation
[INFO]             [ERROR] at initDisplay_Injector.java(15): (initDisplay_Injector$initDisplayTemplateBinder) (initDisplay_Injector$initDisplayTemplateBinder) GWT.create(initDisplay_Injector$initDisplayTemplateBinder.class)
[INFO]                com.google.gwt.dev.jjs.ast.JCastOperation
[INFO]             [ERROR] at initDisplay_Injector.java(15): ((initDisplay_Injector$initDisplayTemplateBinder) (initDisplay_Injector$initDisplayTemplateBinder) GWT.create(initDisplay_Injector$initDisplayTemplateBinder.class)).createAndBindUi(this)
[INFO]                com.google.gwt.dev.jjs.ast.JMethodCall
[INFO]             [ERROR] at initDisplay_Injector.java(15): (Widget) ((initDisplay_Injector$initDisplayTemplateBinder) (initDisplay_Injector$initDisplayTemplateBinder) GWT.create(initDisplay_Injector$initDisplayTemplateBinder.class)).createAndBindUi(this)
[INFO]                com.google.gwt.dev.jjs.ast.JCastOperation
[INFO]             [ERROR] at initDisplay_Injector.java(15): this.initWidget((Widget) ((initDisplay_Injector$initDisplayTemplateBinder) (initDisplay_Injector$initDisplayTemplateBinder) GWT.create(initDisplay_Injector$initDisplayTemplateBinder.class)).createAndBindUi(this))
[INFO]                com.google.gwt.dev.jjs.ast.JMethodCall
[INFO]             [ERROR] at initDisplay_Injector.java(15): this.initWidget((Widget) ((initDisplay_Injector$initDisplayTemplateBinder) (initDisplay_Injector$initDisplayTemplateBinder) GWT.create(initDisplay_Injector$initDisplayTemplateBinder.class)).createAndBindUi(this))
[INFO]                com.google.gwt.dev.jjs.ast.JExpressionStatement
[INFO]             [ERROR] at initDisplay_Injector.java(14): {
[INFO]   super();
[INFO]   this.$init();
[INFO]   this.initWidget((Widget) ((initDisplay_Injector$initDisplayTemplateBinder) (initDisplay_Injector$initDisplayTemplateBinder) GWT.create(initDisplay_Injector$initDisplayTemplateBinder.class)).createAndBindUi(this));
[INFO] }
[INFO]                com.google.gwt.dev.jjs.ast.JBlock
[INFO]             [ERROR] at initDisplay_Injector.java(14): {
[INFO]   super();
[INFO]   this.$init();
[INFO]   this.initWidget((Widget) ((initDisplay_Injector$initDisplayTemplateBinder) (initDisplay_Injector$initDisplayTemplateBinder) GWT.create(initDisplay_Injector$initDisplayTemplateBinder.class)).createAndBindUi(this));
[INFO] }
[INFO]                com.google.gwt.dev.jjs.ast.JMethodBody
[INFO]             [ERROR] at initDisplay_Injector.java(14): public initDisplay_Injector();
[INFO] 
[INFO]                com.google.gwt.dev.jjs.ast.JConstructor
[INFO]       [ERROR] Compiler returned false
[INFO]       [WARN] recompile failed
[INFO]       [WARN] continuing to serve previous version
[INFO] GET /log/colegio
[INFO]    Sent error page: This module hasn't been compiled yet.

**Comment by Dhia1991** [comment]
Hello, 
Did you save the problem ? 

Thanks.

**Comment by javadebian** [comment]
Well I think the error would have to test with gwt 2.8.1 the one that is currently present.
https://groups.google.com/forum/#!topic/putnami-web-toolkit/DQ88Lbj6KWc
